export const authConstant = {
  ADMIN_LOGIN_REQUEST: " ADMIN_LOGIN_REQUEST ",
  ADMIN_LOGIN_SUCCESS: " ADMIN_LOGIN_SUCCESS ",
  ADMIN_LOGIN_FAIL: " ADMION_LOGIN_FAIL ",
  ADMIN_LOGOUT_REQUEST: "ADMIN_LOGOUT_REQUEST",
  ADMIN_LOGOUT_SUCCESS: "ADMIN_LOGOUT_SUCCESS",
  ADMIN_LOGOUT_FAIL: "ADMIN_LOGOUT_FAIL",
};

export const userConstant = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
};

export const categoryConstant = {
  GET_ALL_CATEGORY_REQUEST : 'GET_ALL_CATEGORY_REQUEST',
  GET_ALL_CATEGORY_SUCCESS : 'GET_ALL_CATEGORY_SUCCESS',
  GET_ALL_CATEGORY_FAIL : 'GET_ALL_CATEGORY_FAIL',
  ADD_CATEGORY_REQUEST :'ADD_CATEGORY_REQUEST',
  ADD_CATEGORY_SUCCESS : 'ADD_CATEGORY_SUCCESS',
  ADD_CATEGORY_FAIL :'ADD_CATEGORY_FAIL'

}
