export const authConstant = {
  ADMIN_LOGIN_REQUEST: " ADMIN_LOGIN_REQUEST ",
  ADMIN_LOGIN_SUCCESS: " ADMIN_LOGIN_SUCCESS ",
  ADMIN_LOGIN_FAIL: " ADMION_LOGIN_FAIL ",
  ADMIN_LOGOUT_REQUEST: "ADMIN_LOGOUT_REQUEST",
};

export const userConstant = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
};
